spring.application.name=abarrotes-don-pancho

# PostgreSQL - Neon DB
spring.datasource.url=jdbc:postgresql://ep-fancy-haze-ana477r3-pooler.c-6.us-east-1.aws.neon.tech/abarrotes_don_pancho?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_DpM89xIPzvnT
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
